language: generic

dist: jammy

addons:
  apt:
    update: true
    packages:
      - protobuf-compiler

git clone https://${GITHUB_USER_TOKEN}@github.com/koinos/koinos-proto-cpp.git

jobs:
  include:
    - name: "C++"
      env:
        - TARGET_REPO=koinos-proto-cpp
      script:
        - mkdir build
        - protoc --experimental_allow_proto3_optional --cpp-out=build `find koinos -name '*.proto'` `find google -name '*.proto'` `find openapiv3 -name '*.proto'`
      after_script:
        - git clone https://${GITHUB_USER_TOKEN}@github.com/koinos/${TARGET_REPO}.git
        - cd ${TRAVIS_BUILD_DIR}/
        - mkdir src include
        - rsync -rvm --include "*.pb.cc" --include "*./" --delete ${TRAVIS_BUILD_DIR}/build/cpp/ ./src/
        - rsync -rvm --include "*.pb.h"  --include "*./" --delete ${TRAVIS_BUILD_DIR}/build/cpp/ ./include/
        - git add src include
      after_success:
        - |
          if ! git diff --cached --quiet --exit-code; then
            if [ "${TRAVIS_BRACH}" != "master" ]; then
              git checkout -b ${TRAVIS_BRANCH}
            fi
            git commit -m "Update for koinos-proto commit ${COMMIT_HASH}"
            git push --force https://${GITHUB_USER_TOKEN}@github.com/koinos/${TARGET_REPO}.git ${TRAVIS_BRANCH}
          fi
        - |
          if ! [ -z "${TRAVIS_TAG}" ]; then
            git tag -a ${TRAVIS_TAG} -m "proto tag ${TRAVIS_TAG}"
            git push --force https://${GITHUB_USER_TOKEN}@github.com/koinos/${TARGET_REPO}.git ${TRAVIS_TAG}
          fi

    - name: "Embedded  C++"

    - name: "Protobuf Descriptors"
      env:
       - PB_EMBEDDED_CPP_VERSION="negative-enums"

    - name: "Golang"
  
    - name: "Assembly Script"
      env:
        - AS_PROTO_VERSION="1.0.1"

    - name: "Java Script"

    - name: "Python"

    - name: "Documentation"

notifications:
  slack:
    secure: KUBygLJ3P9z9dYvoWr3Kg+82b5Oq7/gtHmwlv3D+kbzQPJzN/CtwRH9fpJCfa1jjr375tSAb9nbOVqerOHH448aQ50x436Co68Ic2GwQLpfiGjC7apALs2hSxM68nR2+tOPgBk6OCb4rm4G/mnO/2BQqNkGHpk5QoBf5Mv61njyflc5aR5LmlujA2t/5KkXw90te+WDJlwwA08psyhyLjFr/KH7LwDRVc4ggOwDPPPzjwQlABQFyO4avE43SjtSCScMx56y7PdPeIZcvLUo/+lJsCGovS7MTCQ+FPpnHMzYa4QZA7RXTsfys9ZI/SYmrhPdgkBxWOjQCUsO93t8jhikh384li2VqTDTvz0fGh+Cw9LkM80fA+nvaoLAHiUGgI325GmWDnqbEdP9eeFKtRM5U/gTZyEMpDmx/qGr1zmbus31FA+YHPSHsaUYZnzWaCRHOXP7ORm0eiWbczs7jNM0L722EcrocACpZTYFQgy91xr3BAgXOohbN5y+4Uix/BdS4wIHaxNh2N4zzW8v40q0G8lV1Dd2CJKUSbJ27Ze1ziYSQLo4gV9qRULuxiGDdtvlp9Btlz4Rc7NlOrl+oJpl0A0HJFUkalgM5PehmvlPkjJCwdeiCXQdiTe5tO9vPYqifwF+l1kcwIDxc4FBFMbVj2K5C1MAOH+ZjxBNSt1A=
    on_success: never
