name: branch-cleanup

on: [delete]

jobs:
  branch_cleanup:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    env:
      KOINOS_CI_TOKEN: ${{ secrets.KOINOS_CI_TOKEN }}
    steps:
      - run: |
          git clone https://$KOINOS_CI_TOKEN@github.com/koinos/koinos-proto-cpp.git

          pushd koinos-proto-cpp
          git push https://$KOINOS_CI_TOKEN@github.com/koinos/koinos-proto-cpp.git --delete ${{ github.event.ref }}
          popd

          git clone https://$KOINOS_CI_TOKEN@github.com/koinos/koinos-proto-golang.git

          pushd koinos-proto-golang
          git push https://$KOINOS_CI_TOKEN@github.com/koinos/koinos-proto-golang.git --delete ${{ github.event.ref }}
          popd

          git clone https://$KOINOS_CI_TOKEN@github.com/koinos/koinos-proto-js.git

          pushd koinos-proto-js
          git push https://$KOINOS_CI_TOKEN@github.com/koinos/koinos-proto-js.git --delete ${{ github.event.ref }}
          popd
